### ISSUE TITLE
Dear sir please add Add gaana.com, hungama.com,apple music

### ISSUE THREAD

**Issue by anirudhanishal** [sumitkolhe/jiosaavn-api#54] opened 2023-09-04 00:58 UTC
Dear sir please add Add gaana.com, hungama.com,apple music

**Comment by sumitkolhe** [comment] 2024-02-23 17:47
Duplicate of https://github.com/sumitkolhe/jiosaavn-api/issues/53

**Closed by sumitkolhe** 2024-02-23 17:47 UTC
